const SUPABASE_URL=window.CLEAR_LANKA_SUPABASE?.url;
const SUPABASE_ANON_KEY=window.CLEAR_LANKA_SUPABASE?.anonKey;
const client=window.supabase&&SUPABASE_URL&&SUPABASE_ANON_KEY?window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const authRedirect=()=>{const url=new URL('customer.html',location.href);url.search='';url.hash='';return url.href};
const FAV_KEY='clearLankaCustomerFavorites';let mode='signin',currentUser=null;const auth=document.querySelector('#auth-view'),account=document.querySelector('#account-view'),toast=document.querySelector('.toast'),authStatus=document.querySelector('.auth-status');
function notify(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}function setStatus(m,error=false){authStatus.textContent=m;authStatus.classList.toggle('error',error)}
function showAccount(user){currentUser=user;auth.hidden=true;document.querySelector('body>header').hidden=true;account.hidden=false;loadProfile()}function showAuth(){currentUser=null;account.hidden=true;auth.hidden=false;document.querySelector('body>header').hidden=false}
document.querySelectorAll('[data-auth]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.auth;document.querySelectorAll('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));const up=mode==='signup';document.querySelector('.name-field').hidden=!up;document.querySelector('#auth-title').textContent=up?'Create your account':'Welcome back';document.querySelector('#auth-copy').textContent=up?'Create a secure traveller login.':'Sign in to your traveller account.';document.querySelector('#auth-submit').textContent=up?'Create account →':'Sign in securely →';document.querySelector('[name="password"]').autocomplete=up?'new-password':'current-password';setStatus('')}));
document.querySelector('#customer-auth').addEventListener('submit',async e=>{e.preventDefault();if(!client)return setStatus('Authentication library could not load. Check your connection.',true);const data=new FormData(e.target),email=data.get('email'),password=data.get('password'),name=data.get('name');try{if(mode==='recovery'){const {error}=await client.auth.updateUser({password});if(error)throw error;setStatus('Password updated. Your account is ready.');const {data:sessionData,error:sessionError}=await client.auth.getSession();if(sessionError)throw sessionError;if(sessionData.session?.user)showAccount(sessionData.session.user);return}setStatus(mode==='signup'?'Creating your account…':'Signing you in…');const result=mode==='signup'?await client.auth.signUp({email,password,options:{data:{display_name:name||''},emailRedirectTo:authRedirect()}}):await client.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(mode==='signup'&&!result.data.session){setStatus('Check your email to confirm your account. Delivery and redirects depend on Supabase email settings.');e.target.reset();return}if(!result.data.user)throw new Error('Sign-in did not return a valid user.');setStatus('');showAccount(result.data.user);notify('Signed in securely')}catch(error){setStatus(error.message||'Authentication request failed.',true)}});
document.querySelector('#forgot-password').addEventListener('click',async()=>{const email=document.querySelector('[name="email"]').value;if(!email)return setStatus('Enter your email address first.',true);if(!client)return setStatus('Authentication library could not load.',true);try{const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:authRedirect()});if(error)throw error;setStatus('If the address is registered, Supabase will send reset instructions.')}catch(error){setStatus(error.message||'Could not request a password reset.',true)}});
document.querySelector('#customer-logout').addEventListener('click',async()=>{if(client)await client.auth.signOut();showAuth();notify('Signed out')});
function openPanel(name){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.view===name));document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));document.querySelector('#panel-title').textContent=document.querySelector(`[data-panel="${name}"]`)?.textContent.trim()||'Overview';document.querySelector('.account>aside').classList.remove('open')}
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.go)));document.querySelector('.menu').addEventListener('click',()=>document.querySelector('.account>aside').classList.toggle('open'));
let favorites=JSON.parse(localStorage.getItem(FAV_KEY)||'["airport","guide"]');function renderFavs(){document.querySelectorAll('[data-favorite]').forEach(card=>{const saved=favorites.includes(card.dataset.favorite),btn=card.querySelector('button');btn.textContent=saved?'♥ Saved':'♡ Save';btn.className=saved?'remove':'save'});document.querySelector('#saved-count').textContent=favorites.length}document.querySelectorAll('[data-favorite] button').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.closest('[data-favorite]').dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem(FAV_KEY,JSON.stringify(favorites));renderFavs();notify('Favourites updated on this device')}));renderFavs();
async function loadProfile(){if(!currentUser)return;document.querySelector('[data-profile="email"]').value=currentUser.email||'';document.querySelector('[data-profile="name"]').value=currentUser.user_metadata?.display_name||'';if(!client)return;const {data,error}=await client.from('customer_profiles').select('display_name,country,travel_style,notes').eq('id',currentUser.id).maybeSingle();if(error)return notify('Profile could not be loaded.');if(data){document.querySelector('[data-profile="name"]').value=data.display_name||'';document.querySelector('[data-profile="country"]').value=data.country||'';document.querySelector('[data-profile="style"]').value=data.travel_style||'Balanced';document.querySelector('[data-profile="notes"]').value=data.notes||''}}
document.querySelector('#save-profile').addEventListener('click',async()=>{if(!client||!currentUser)return notify('Sign in before saving');const row={id:currentUser.id,display_name:document.querySelector('[data-profile="name"]').value,country:document.querySelector('[data-profile="country"]').value,travel_style:document.querySelector('[data-profile="style"]').value,notes:document.querySelector('[data-profile="notes"]').value,updated_at:new Date().toISOString()};const {error}=await client.from('customer_profiles').upsert(row);notify(error?'Profile table is not ready; run the included migration.':'Profile saved securely')});
if(client){client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){mode='recovery';showAuth();document.querySelector('.tabs').hidden=true;document.querySelector('.name-field').hidden=true;document.querySelector('[name="email"]').closest('label').hidden=true;document.querySelector('#forgot-password').hidden=true;document.querySelector('#auth-title').textContent='Choose a new password';document.querySelector('#auth-copy').textContent='Enter at least 8 characters for your new password.';document.querySelector('#auth-submit').textContent='Update password →';return}session?.user?showAccount(session.user):showAuth()});client.auth.getSession().then(({data})=>{if(data.session?.user)showAccount(data.session.user)})}else setStatus('Authentication library could not load. Check your connection.',true);
